### PR TITLE
Add support for Active Record 5.2

### LINKED ISSUE #85: Rails 5.2 support
It looks like baby_squeel isn't working with joins in rails 5.2.0.beta2.

### PR DESCRIPTION
**Pull request by rzane**
🎉 This has been much easier than I had expected!

There are only two remaining issues:
* [ ] Polymorphic associations
* [x] `BabySqueel::Association#!` spec is broken

Fixes #85.

### CODE REVIEW

**Comment by rzane** [comment]
Okay, seems like this all comes down to https://github.com/activerecord-hackery/polyamorous/issues/37.

**Comment by rainerborene** [comment]
@rzane master branch is already usable? i can't use it yet.

```ruby
gem "join_dependency", github: "rzane/join_dependency"
gem "baby_squeel", github: "rzane/baby_squeel"
```

```
ArgumentError: wrong number of arguments (given 3, expected 2)
  /home/rainer/.asdf/installs/ruby/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/baby_squeel-924cfe4b0373/lib/baby_squeel/active_record/query_methods.rb:43:in `build_joins'
  /home/rainer/.asdf/installs/ruby/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation/query_methods.rb:928:in `build_arel'
  /home/rainer/.asdf/installs/ruby/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation/query_methods.rb:903:in `arel'
  /home/rainer/.asdf/installs/ruby/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation.rb:554:in `block in exec_queries'
  /home/rainer/.asdf/installs/ruby/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation.rb:578:in `skip_query_cache_if_necessary'
  /home/rainer/.asdf/installs/ruby/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation.rb:542:in `exec_queries'
  /home/rainer/.asdf/installs/ruby/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation.rb:414:in `load'
  /home/rainer/.asdf/installs/ruby/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation.rb:200:in `records'
  /home/rainer/.asdf/installs/ruby/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation/finder_methods.rb:502:in `find_take'
  /home/rainer/.asdf/installs/ruby/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation/finder_methods.rb:103:in `take'
  /home/rainer/Projects/memberkit/app/models/user/custom_devise.rb:33:in `find_for_authentication'
```

**Comment by Schwad** [comment]
Okay, I am also pointing to this branch. @rzane, feel free to @ message me when it's ready, or if there's anything else I can do to help!!!

**Comment by Schwad** [comment]
Also @rzane just going to say that I tried to point to your branch but it broke because of the sqlite3 dependency on `join_dependency`.... This may be very dangerous but I am forking it to see how things run without that dependency.... 🙊

**Comment by rzane** [comment]
Oh whoops, that was an accident. Sqlite is definitely not a real dependency. I'll fix that today.

**Comment by rzane** [comment]
Released: https://rubygems.org/gems/baby_squeel/versions/1.2.1

**Comment by Schwad** [comment]
@rzane Awesome!!! Thank you so much!!!

**Comment by ConnerMan** [comment]
Much appreciated @rzane! 👍

**Pull request merged**
